spring:
  jpa:
    # jpa ?? sql ??
    show-sql: true
    hibernate:
      # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none, ?? ??? ??? - update
      ddl-auto: create

  # H2 ??? DB ??
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2
      # localhost:port/h2
      settings:
        # ?? ?? ?? ??
        trace: false
        #????? ??
        web-allow-others: true

  profiles:
    active: local